// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
// WARNING (WR-04): This auto-generated file uses bigint for beat/total_beats (Rust u64).
// shared/protocol.ts is AUTHORITATIVE and uses number. Do not import from this file
// in application code — regenerate after adding #[ts(type = "number")] to protocol.rs fields.

export type MsgDanceBeat = { type: string, beat: bigint, total_beats: bigint,
/**
 * Per-keypoint data as [x, y, z, visibility]. Matches the json!() payload from
 * DancePlugin::on_tick: `[kp.x, kp.y, kp.z, kp.visibility]` per keypoint.
 */
target_pose: Array<[number, number, number, number]>, };
