// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
// WARNING (WR-04): This auto-generated file uses bigint for beat (Rust u64).
// shared/protocol.ts is AUTHORITATIVE and uses number. Do not import from this file
// in application code — regenerate after adding #[ts(type = "number")] to protocol.rs fields.

export type MsgDanceScore = { type: string, beat: bigint,
/**
 * Cumulative similarity scores for [player_1, player_2]. Range [0.0, 1.0].
 */
scores: [number, number], };
