// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MsgJoined = { type: string, room_code: string, player_slot: number, opponent_connected: boolean, };
