// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MsgRoundEnd = { type: string, 
/**
 * null means draw; 1 or 2 is the winning player
 */
winner: number | null, final_hp: [number, number], };
