// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HitEvent } from "./HitEvent";
import type { PoseKeypoint } from "./PoseKeypoint";

export type MsgGameState = { type: string, tick: bigint, hp: [number, number], 
/**
 * FIX-02: wins counter in snapshot prevents overlay desync on reconnect
 */
wins: [number, number], poses: [Array<PoseKeypoint>, Array<PoseKeypoint>], recent_hits: Array<HitEvent>, high_latency: boolean, remaining_time: number, max_wins: number, };
